### ISSUE TITLE
pogo - podman GitLab CI executor

### ISSUE THREAD

**Issue by unused** [gograz/ping#4]
## Topic

Happy to given an overview on [pogo](https://github.com/eyeson-team/pogo), a custom GitLab executor using [podman](https://podman.io/) - user-level containers(!) - that is based on spf13 cobra and viper. It is a very straightforward way of running GitLab CI jobs on your local computer, some unused machine or to easily build runners for self hosted instances w/o Docker.

## Format

Lightning talk might be enough to explain how it works. A workshop demo might take a session of about 30 minutes.

**Comment by zerok** [comment]
That sounds awesome! Do you perhaps want to give that talk in March?

**Comment by unused** [comment]
March is perfect :+1:  thanks!
