### ISSUE TITLE
IaC quick ArgoCD Demo 

### ISSUE THREAD

**Issue by rwese** [gograz/ping#7]
I'd try to prepare a quick demo project, can't fully promise anything yet as I am still ironing it out.

## Topic

From a empty k8s(or equivalent) to an Infrastructure repository with Ingress, Secrets, Services

Using helm, argocd, external secrets, external dns

## Format

🌩️ Lightning

**Comment by zerok** [comment]
Hey! 🙂 Do you think it's realistic for our Oct 15 meetup?

**Comment by rwese** [comment]
Hi, i think so, i aim to only show off my setup, hopefully with a realistic demo.

It will be my first talk in this style. :fearful:

**Comment by rwese** [comment]
I am unable to prepare for this meetup, sorry! @zerok

**Comment by zerok** [comment]
No worries 🙂
